BanMoHinh.Client/Areas/Admin/Controllers/HomeController.cs
using BanMoHinh.Share.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BanMoHinh.Client.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {
        private readonly HttpClient _httpClient;

        public HomeController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string startDate, string endDate)
        {
            try
            {
                if (startDate == null || endDate == null)
                {
                    startDate = DateTime.Now.AddDays(-7).ToString();
                    endDate = DateTime.Now.ToString();
                }
                var response = await _httpClient.GetAsync("https://localhost:7007/api/ThongKe/ThongKe?startDate=" + startDate + "&endDate=" + endDate);
                var lst = JsonConvert.DeserializeObject<ThongKeViewModel>(response.Content.ReadAsStringAsync().Result);
                return View(lst);
            }
            catch
            {
                return View(new ThongKeViewModel());
            }
        }
    }
}

BanMoHinh.Client/Controllers/HomeController.cs
using BanMoHinh.Client.Models;
using BanMoHinh.Share.Models;
using BanMoHinh.Share.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Net.Http;

namespace BanMoHinh.Client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly HttpClient _httpClient;

        public HomeController(ILogger<HomeController> logger, HttpClient httpClient)
        {
            _logger = logger;
            _httpClient = httpClient;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _httpClient.GetFromJsonAsync<List<ProductVM>>("https://localhost:7007/api/product/get-all-productvm");
            var productDetail = await _httpClient.GetFromJsonAsync<List<ProductDetailVM>>("https://localhost:7007/api/productDetail/get-all-productdetail");
            var ProductImage = await _httpClient.GetFromJsonAsync<List<ProductImage>>("https://localhost:7007/api/productimage/get-all-productimage");
            // Sắp xếp để lấy ra 4 sản phẩm mới nhất (theo ngày tạo)
            var newestProducts = result
            .OrderByDescending(pd => pd.Create_At)
            .GroupBy(pd => new { pd.BrandId, pd.MaterialId, pd.CategoryId }) // Nhóm theo các thuộc tính 
            .Select(group => group.First()) // Lấy phần tử đầu tiên từ mỗi nhóm
            .Take(4)
            .ToList();

            ViewData["NewestProducts"] = newestProducts;
            ViewData["productDetail"] = productDetail;
            ViewData["ProductImage"] = ProductImage;
            if (newestProducts != null)
            {
                ViewData["NewestProducts"] = newestProducts;
            }
            else
            {
                TempData["Message"] = "Dữ liệu không tồn tại.";
            }
            
            return View();
        }
        public IActionResult Introduct()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BanMoHinh.Client/Controllers/OrderController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BanMoHinh.Share.Models;
using BanMoHinh.Share.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Security.Claims;
using X.PagedList;

namespace BanMoHinh.Client.Controllers
{
	public class OrderController : Controller
	{
		private readonly HttpClient _httpClient;
        public INotyfService _notyf;

        public OrderController(HttpClient httpClient, INotyfService notyf)
        {
            _httpClient = httpClient;
            _notyf = notyf;
        }

        public async Task<IActionResult> allOrder(Guid id, int? page,int status)
        {

            if (page == null) page = 1;
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            ViewBag.status = status;

            var identity = HttpContext.User.Identity as ClaimsIdentity;
            var userIdClaim = identity.FindFirst(ClaimTypes.Name);
            var userName = userIdClaim.Value;
            var getUserbyName = await _httpClient.GetFromJsonAsync<User>($"https://localhost:7007/api/users/get/{userName}");
            var listOrder = await _httpClient.GetFromJsonAsync<List<Order>>("https://localhost:7007/api/order/getall");
            var listorderbyUser = listOrder.Where(c => c.UserId == getUserbyName.Id).OrderByDescending(c=>c.Create_Date);
            
            if (status==-1)
            {
                listorderbyUser = listOrder.Where(c => c.UserId == getUserbyName.Id&& c.OrderStatusId == Guid.Parse("9C54C2DD-2FA5-4041-9B94-FB613BEBDFBC")).OrderByDescending(c => c.Create_Date);

            }
            if (status==0)
            {
                listorderbyUser = listOrder.Where(c => c.UserId == getUserbyName.Id).OrderByDescending(c => c.Create_Date);
            }
            if (status==1)
            {
                listorderbyUser = listOrder.Where(c => c.UserId == getUserbyName.Id&& c.OrderStatusId == Guid.Parse("1C54C2DD-2FA5-4041-9B94-FB613BEBDFBC")).OrderByDescending(c => c.Create_Date);
            }
            if (status==2)
            {
                listorderbyUser = listOrder.Where(c => c.UserId == getUserbyName.Id&& c.OrderStatusId == Guid.Parse("2C54C2DD-2FA5-4041-9B94-FB613BEBDFBC")).OrderByDescending(c => c.Create_Date);
            }
            if (status==3)
            {
                listorderbyUser = listOrder.Where(c => c.UserId == getUserbyName.Id&& c.OrderStatusId == Guid.Parse("3C54C2DD-2FA5-4041-9B94-FB613BEBDFBC")).OrderByDescending(c => c.Create_Date);
            }
            if (status==4)
            {
                listorderbyUser = listOrder.Where(c => c.UserId == getUserbyName.Id&& c.OrderStatusId == Guid.Parse("4C54C2DD-2FA5-4041-9B94-FB613BEBDFBC")).OrderByDescending(c => c.Create_Date);
            }
            if (status==5)
            {
                listorderbyUser = listOrder.Where(c => c.UserId == getUserbyName.Id&& c.OrderStatusId == Guid.Parse("6C54C2DD-2FA5-4041-9B94-FB613BEBDFBC")).OrderByDescending(c => c.Create_Date);
            }

            return View(listorderbyUser.ToPagedList(pageNumber, pageSize));

        }
        public IActionResult OrderDetails(Guid idHoaDon)
        {
            
                List<DonMuaChiTietVM> DonMuaCT = new List<DonMuaChiTietVM>();
                HttpResponseMessage responseDonMuaCT =  _httpClient.GetAsync($"https://localhost:7007/api/order/GetAllDonMuaChiTiet?idHoaDon={idHoaDon}").Result;
                if (responseDonMuaCT.IsSuccessStatusCode)
                {
                    DonMuaCT = JsonConvert.DeserializeObject<List<DonMuaChiTietVM>>(responseDonMuaCT.Content.ReadAsStringAsync().Result);
                }
                return View("OrderDetails", DonMuaCT);
            
        }
        public async Task<IActionResult> HuyDon(Guid idHoaDon, Guid? idTrangThai)
        {
            var listOrder = await _httpClient.GetFromJsonAsync<List<Order>>("https://localhost:7007/api/order/getall");
            
            var firstOrder = listOrder.FirstOrDefault();
            if (firstOrder != null)
            {
                idTrangThai = firstOrder.OrderStatusId = Guid.Parse("6C54C2DD-2FA5-4041-9B94-FB613BEBDFBC");//huỷ đơn
            }
            //update trạng thái hoá đơn
            HttpResponseMessage responseDonMua = await _httpClient.GetAsync($"https://localhost:7007/api/order/updatestatus?OrderId={idHoaDon}&StatusId={idTrangThai}");
            
            if (responseDonMua.IsSuccessStatusCode)
            {
                //hoàn lại voucher
                if (firstOrder.VoucherId != null)
                {
                    // + số lượng voucher 

                    var updateSL = await _httpClient.GetAsync($"https://localhost:7007/api/voucher/TangGiamSoLuongTheoId?voucherId={firstOrder.VoucherId}&tanggiam=true");

                    //  sửa trạng thái trong uservoucher  

                    var updateStatus = await _httpClient.GetAsync($" https://localhost:7007/api/UserVoucher/updatetrangthai?voucherId={firstOrder.VoucherId}&userId={firstOrder.UserId}&status=true");

                }
                //hoàn lại số lượng
                //var listOrderItem = await _httpClient.GetFromJsonAsync<List<OrderItem>>("https://localhost:7007/api/orderitem/getall");           
                
                //var lsthdct = listOrderItem.Where(c => c.OrderId == idHoaDon).ToList();
                //foreach (var hdct in lsthdct)
                //{
                //    var UpdateQ = await _httpClient.GetAsync($"https://localhost:7007/api/productDetail/UpdateQuantityOrderFail?productDetailId={hdct.ProductDetailId}&quantity={hdct.Quantity}");// update lại sp
                //}
                //var updateSLSPfromDb = await _httpClient.GetAsync($"https://localhost:7007/api/product/UpdateSLTheoSPCT");
                return RedirectToAction("allOrder");
            }

            return RedirectToAction("allOrder");
        }

        public async Task<IActionResult> allOrderCode(string ordercode)
        {
            if (string.IsNullOrEmpty(ordercode))
            {
                _notyf.Warning("Mã đơn hàng không được để trống.");
                return RedirectToAction("SearchOrderCode");
            }
            var listOrder = await _httpClient.GetFromJsonAsync<QLHDViewModel>($"https://localhost:7007/api/order/GetAllDonMuaByOrderCode?orderCode={ordercode}");

            return View(listOrder);
        }

        public async Task<IActionResult> SearchOrderCode()
        {

            return View();

        }



    }
}

BanMoHinh.Client/Controllers/UserController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BanMoHinh.Share.Models;
using BanMoHinh.Share.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Net.Mail;
using System.Security.Claims;

namespace BanMoHinh.Client.Controllers
{
    public class UserController : Controller
    {
        public INotyfService _notyf;

        private readonly HttpClient _httpClient;

        public UserController(HttpClient httpClient, INotyfService notyf)
        {
            _httpClient = httpClient;
            _notyf = notyf;
        }
        private bool IsValidEmail(string email)
        {
            try
            {
                var mailAddress = new MailAddress(email);
                return true;
            }
            catch (FormatException)
            {
                return false;
            }
        }
        [HttpGet]

        public async Task<IActionResult> Profile(Guid id)
        {
            var identity = HttpContext.User.Identity as ClaimsIdentity;



            var userID = Guid.Parse(identity.FindFirst(ClaimTypes.NameIdentifier).Value);
            ViewBag.userID = userID;
            var user = await _httpClient.GetFromJsonAsync<User>($"https://localhost:7007/api/users/getID/{id}");
            var ranks = await _httpClient.GetFromJsonAsync<List<Rank>>("https://localhost:7007/api/ranks/get-ranks");

            ViewData["rank"] = ranks;
            return View(user);

        }

        [HttpPost]

        public async Task<IActionResult> Profile(UserViewModel user)
        {

            if (user.PhoneNumber.Length > 11)
            {
                _notyf.Error("Số điện thoại không quá 10 số");
            }
            if (!IsValidEmail(user.Email))
            {
                _notyf.Error("Email không hợp lệ");

            }
            if (user.DateOfBirth > DateTime.Now || user.DateOfBirth < new DateTime(1900, 1, 1))
            {
                _notyf.Error("ngày sinh không hợp lệ, ngày sinh phải nhỏ hơn hiện tại và ko được thấp hơn năm 1900");

            }
            var identity = HttpContext.User.Identity as ClaimsIdentity;
            var usernameClaim = identity.FindFirst(ClaimTypes.Name);

            if (usernameClaim != null)
            {
                var username = usernameClaim.Value;
                user.UserName = username;
                var result = await _httpClient.PutAsJsonAsync($"https://localhost:7007/api/users/Update", user);
                if (result.IsSuccessStatusCode)
                {
                    _notyf.Success("Cập nhật thành công");
                    return RedirectToAction("Index", "Home");

                }
                // Sử dụng biến username ở đây
            }


            _notyf.Error("Cập nhật thất bại");
            return RedirectToAction("Profile");

        }


    }
    
}

BanMoHinh.Client/Areas/Admin/Views/Home/Index.cshtml
@using BanMoHinh.Share.ViewModels

@model ThongKeViewModel
@{
    ViewData["Title"] = "ThongKe";
    Layout = "~/Areas/Admin/Shared/_LayoutAdmin.cshtml";
}

<style>
    .customer-list {
        list-style: none;
        padding: 0;
    }

        .customer-list li {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 8px;
            border-bottom: 1px solid #ddd; /* Đường kẻ giữa các hàng */
        }

            .customer-list li:last-child {
                border-bottom: none; /* Loại bỏ đường kẻ ở hàng cuối cùng */
            }


            .customer-list li .sdt,
            .customer-list li .tongtien,
            .customer-list li .tonghoadon {
                flex-grow: 1;
                margin-right: 8px;
            }


</style>

<div class="row">
    <div class="col-md-3">
        <div class="card text-white bg-secondary mb-3" >
            <div class="card-header">Số lượng thành viên</div>
            <div class="card-body">
                <h5 class="card-title">@Model.SoLuongThanhVien</h5>
                <a style="color:white" asp-area="Admin" asp-controller="User" asp-action="Index"> <p class="card-text">Xem thêm</p> </a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card text-white bg-success mb-3" >
            <div class="card-header">Số đơn hàng chờ</div>
            <div class="card-body">
                <h5 class="card-title">@Model.SoLuongDonHang</h5>
                <a style="color:white" asp-area="Admin" asp-controller="Order" asp-action="ShowList"> <p class="card-text">Xem thêm</p> </a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card text-dark bg-info mb-3" >
            <div class="card-header">Số lượng sản phẩm trong kho</div>
            <div class="card-body">
                <h5 class="card-title">@Model.SoLuongSanPham</h5>
                <a style="color:white" asp-area="Admin" asp-controller="Product" asp-action="GetAllProduct"> <p class="card-text">Xem thêm</p> </a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card text-white bg-danger mb-3">
            <div class="card-header">Số lượng đơn bị huỷ</div>
            <div class="card-body">
                <h5 class="card-title">@Model.SoLuongDonHuy</h5>
                <a style="color:white" asp-area="Admin" asp-controller="Order" asp-action="ShowList"> <p class="card-text">Xem thêm</p> </a>
            </div>
        </div>
    </div>
</div>
    
<div class="row">
    <div class="d-flex justify-content-end" style="margin-right:10px;margin-bottom:10px">
        <p style="margin-right:10px">Thời gian:</p><input type="text" id="daterange" value="12/01/2024 - 12/31/2024" class="form-control" style="width:30%;" />
    </div>
    <div class="col-lg-12">
        <div class="card">
            
            <div class="card-block">
                <canvas id="barChart" class="ct-chart-line " style="width: 100%!important; height: 330px; margin: 0 auto"></canvas>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-8 col-lg-12">
        <div class="card" style="height:300px">
            <div class="card-block">
                <canvas id="lineChart" style="width: 90%; height: 230px; margin: 0 auto"></canvas>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-12">
        <div class="card" style="height:300px">
            <div class="card-block">
                <h3 style="margin:8px">Top khách mua nhiều</h3>
                <ul class="customer-list">
                    @{
                        @foreach (var khachHang in Model.topKhachHang.OrderByDescending(kh => kh.tongtien))
                        {
                            <li>
                                <span class="sdt">SDT: @khachHang.sdt</span>
                                <span class="tongtien">Tổng tiền: @khachHang.tongtien?.ToString("n0")</span>
                                <span class="tonghoadon">Tổng đơn: @khachHang.tonghoadon</span>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>

</div>
<!-- 2-1 block end -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(function () {
        $('#daterange').daterangepicker({
            opens: 'left',
            startDate: '@Model.Start',
            endDate: '@Model.End'
        }, function (start, end, label) {
            location.href = "/Admin/Home/Index?startDate=" + start.format('YYYY-MM-DD') + "&endDate=" + end.format('YYYY-MM-DD');
        });
    });
    @{
        var colorPalette = new[] { "#FF5733", "#33FF57", "#5733FF", "#FF33A8", "#33A8FF" };
    }

    var labelBars = [];
    var dataBars = [];
    var backgroundColors = [];

    @for (int i = 0; i < Model.BieuDoCot.Count; i++)
    {
        var x = Model.BieuDoCot[i];
        @:labelBars.push('@Html.Raw(x.TenSP)')
        @:dataBars.push(@x.SoLuong)

        // Chọn màu từ mảng màu và thêm vào mảng backgroundColors
        @:backgroundColors.push('@colorPalette[i % colorPalette.Length]')
    }

    var barChart = new Chart(document.getElementById('barChart'), {
        type: 'bar',
        data: {
            labels: labelBars,
            datasets: [{
                label: 'Sản phẩm bán chạy',
                data: dataBars,
                backgroundColor: backgroundColors,
                borderColor: 'rgba(0, 123, 255, 1)',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });


    var labelLines = [];
    var dataLines = [];
    var dataProfit = []; 

    @foreach (var x in Model.BieuDoDuong)
    {
        @:labelLines.push('@x.Ngay.ToString("MM/dd/yyyy")')
        @:dataLines.push(@x.DoanhThu)
        @:dataProfit.push(@x.LoiNhuan) // Giả sử bạn có dữ liệu lợi nhuận trong Model.BieuDoDuong
    }

    var lineChart = new Chart(document.getElementById('lineChart'), {
        type: 'line',
        data: {
            labels: labelLines,
            datasets: [
                {
                    label: 'Doanh thu',
                    data: dataLines,
                    backgroundColor: 'rgba(255, 99, 132, 0.2)',
                    borderColor: 'rgba(255, 99, 132, 1)',
                    borderWidth: 1
                },
                {
                    label: 'Lợi nhuận',
                    data: dataProfit,
                    backgroundColor: 'rgba(54, 162, 235, 0.2)',
                    borderColor: 'rgba(54, 162, 235, 1)',
                    borderWidth: 1
                }
            ]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });



</script>
<script>
    var $window = $(window);
    var nav = $('.fixed-button');
    $window.scroll(function () {
        if ($window.scrollTop() >= 200) {
            nav.addClass('active');
        }
        else {
            nav.removeClass('active');
        }
    });
</script>